cd main_code

export GPU_IDS="4,5,6,7"
export NUM_TEST=1024
export NUM_GPU=4
export BATCH_SIZE=256
export CLSSIFIER=t7

# CUDA_VISIBLE_DEVICES=$GPU_IDS python -m torch.distributed.launch --nproc_per_node=$NUM_GPU --master_port=31369 ddim_attack_eval_lock_l2.py --model_id ../../train/ddpm-cifar10-100e-l2-clip10-pretrained-lkz-resample --save_folder clip10_l2_resample --num_test $NUM_TEST  --batch_size $BATCH_SIZE --inference_step 50    --model_type $CLSSIFIER 
# CUDA_VISIBLE_DEVICES=$GPU_IDS python -m torch.distributed.launch --nproc_per_node=$NUM_GPU --master_port=31369 ddim_attack_eval_lock_l2.py --model_id ../../train/ddpm-cifar10-100e-l2-clip10-pretrained-lkz-resample --save_folder clip10_l2_resample --num_test $NUM_TEST  --batch_size $BATCH_SIZE --inference_step 100   --model_type $CLSSIFIER 
# CUDA_VISIBLE_DEVICES=$GPU_IDS python -m torch.distributed.launch --nproc_per_node=$NUM_GPU --master_port=31369 ddim_attack_eval_lock_l2.py --model_id ../../train/ddpm-cifar10-100e-l2-clip10-pretrained-lkz-resample --save_folder clip10_l2_resample --num_test $NUM_TEST  --batch_size $BATCH_SIZE --inference_step 200   --model_type $CLSSIFIER 
# CUDA_VISIBLE_DEVICES=$GPU_IDS python -m torch.distributed.launch --nproc_per_node=$NUM_GPU --master_port=31369 ddim_attack_eval_lock_l2.py --model_id ../../train/ddpm-cifar10-100e-l2-clip10-pretrained-lkz-resample --save_folder clip10_l2_resample --num_test $NUM_TEST  --batch_size $BATCH_SIZE --inference_step 500   --model_type $CLSSIFIER 
# CUDA_VISIBLE_DEVICES=$GPU_IDS python -m torch.distributed.launch --nproc_per_node=$NUM_GPU --master_port=31369 ddim_attack_eval_lock_l2.py --model_id ../../train/ddpm-cifar10-100e-l2-clip10-pretrained-lkz-resample --save_folder clip10_l2_resample --num_test $NUM_TEST  --batch_size $BATCH_SIZE --inference_step 1000  --model_type $CLSSIFIER 

# CUDA_VISIBLE_DEVICES=$GPU_IDS python -m torch.distributed.launch --nproc_per_node=$NUM_GPU --master_port=31369 ddim_attack_eval_lock_l2.py --model_id ../../train/ddpm-cifar10-100e-l2-clip5-pretrained-lkz-resample --save_folder clip5_l2_resample --num_test $NUM_TEST  --batch_size $BATCH_SIZE --inference_step 50    --model_type $CLSSIFIER 
# CUDA_VISIBLE_DEVICES=$GPU_IDS python -m torch.distributed.launch --nproc_per_node=$NUM_GPU --master_port=31369 ddim_attack_eval_lock_l2.py --model_id ../../train/ddpm-cifar10-100e-l2-clip5-pretrained-lkz-resample --save_folder clip5_l2_resample --num_test $NUM_TEST  --batch_size $BATCH_SIZE --inference_step 100   --model_type $CLSSIFIER 
# CUDA_VISIBLE_DEVICES=$GPU_IDS python -m torch.distributed.launch --nproc_per_node=$NUM_GPU --master_port=31369 ddim_attack_eval_lock_l2.py --model_id ../../train/ddpm-cifar10-100e-l2-clip5-pretrained-lkz-resample --save_folder clip5_l2_resample --num_test $NUM_TEST  --batch_size $BATCH_SIZE --inference_step 200   --model_type $CLSSIFIER 
# CUDA_VISIBLE_DEVICES=$GPU_IDS python -m torch.distributed.launch --nproc_per_node=$NUM_GPU --master_port=31369 ddim_attack_eval_lock_l2.py --model_id ../../train/ddpm-cifar10-100e-l2-clip5-pretrained-lkz-resample --save_folder clip5_l2_resample --num_test $NUM_TEST  --batch_size $BATCH_SIZE --inference_step 500   --model_type $CLSSIFIER 
# CUDA_VISIBLE_DEVICES=$GPU_IDS python -m torch.distributed.launch --nproc_per_node=$NUM_GPU --master_port=31369 ddim_attack_eval_lock_l2.py --model_id ../../train/ddpm-cifar10-100e-l2-clip5-pretrained-lkz-resample --save_folder clip5_l2_resample --num_test $NUM_TEST  --batch_size $BATCH_SIZE --inference_step 1000  --model_type $CLSSIFIER 

# CUDA_VISIBLE_DEVICES=$GPU_IDS python -m torch.distributed.launch --nproc_per_node=$NUM_GPU --master_port=31369 ddim_attack_eval_lock_l2.py --model_id ../../train/ddpm-cifar10-100e-l2-clipinf-pretrained-lkz-resample --save_folder clipinf_l2_resample --num_test $NUM_TEST  --batch_size $BATCH_SIZE --inference_step 50    --model_type $CLSSIFIER 
# CUDA_VISIBLE_DEVICES=$GPU_IDS python -m torch.distributed.launch --nproc_per_node=$NUM_GPU --master_port=31369 ddim_attack_eval_lock_l2.py --model_id ../../train/ddpm-cifar10-100e-l2-clipinf-pretrained-lkz-resample --save_folder clipinf_l2_resample --num_test $NUM_TEST  --batch_size $BATCH_SIZE --inference_step 100   --model_type $CLSSIFIER 
# CUDA_VISIBLE_DEVICES=$GPU_IDS python -m torch.distributed.launch --nproc_per_node=$NUM_GPU --master_port=31369 ddim_attack_eval_lock_l2.py --model_id ../../train/ddpm-cifar10-100e-l2-clipinf-pretrained-lkz-resample --save_folder clipinf_l2_resample --num_test $NUM_TEST  --batch_size $BATCH_SIZE --inference_step 200   --model_type $CLSSIFIER 
# CUDA_VISIBLE_DEVICES=$GPU_IDS python -m torch.distributed.launch --nproc_per_node=$NUM_GPU --master_port=31369 ddim_attack_eval_lock_l2.py --model_id ../../train/ddpm-cifar10-100e-l2-clipinf-pretrained-lkz-resample --save_folder clipinf_l2_resample --num_test $NUM_TEST  --batch_size $BATCH_SIZE --inference_step 500   --model_type $CLSSIFIER 
# CUDA_VISIBLE_DEVICES=$GPU_IDS python -m torch.distributed.launch --nproc_per_node=$NUM_GPU --master_port=31369 ddim_attack_eval_lock_l2.py --model_id ../../train/ddpm-cifar10-100e-l2-clipinf-pretrained-lkz-resample --save_folder clipinf_l2_resample --num_test $NUM_TEST  --batch_size $BATCH_SIZE --inference_step 1000  --model_type $CLSSIFIER 

# CUDA_VISIBLE_DEVICES=$GPU_IDS python -m torch.distributed.launch --nproc_per_node=$NUM_GPU --master_port=38369 ddim_attack_eval_lock_l2.py --model_id ../../train/ddpm_ema_cifar10 --save_folder clean_model_l2 --num_test $NUM_TEST  --batch_size $BATCH_SIZE --inference_step 50    --model_type $CLSSIFIER 
# CUDA_VISIBLE_DEVICES=$GPU_IDS python -m torch.distributed.launch --nproc_per_node=$NUM_GPU --master_port=38369 ddim_attack_eval_lock_l2.py --model_id ../../train/ddpm_ema_cifar10 --save_folder clean_model_l2 --num_test $NUM_TEST  --batch_size $BATCH_SIZE --inference_step 100   --model_type $CLSSIFIER 
# CUDA_VISIBLE_DEVICES=$GPU_IDS python -m torch.distributed.launch --nproc_per_node=$NUM_GPU --master_port=38369 ddim_attack_eval_lock_l2.py --model_id ../../train/ddpm_ema_cifar10 --save_folder clean_model_l2 --num_test $NUM_TEST  --batch_size $BATCH_SIZE --inference_step 200   --model_type $CLSSIFIER 
CUDA_VISIBLE_DEVICES=$GPU_IDS python -m torch.distributed.launch --nproc_per_node=$NUM_GPU --master_port=38369 ddim_attack_eval_lock_l2.py --model_id ../../train/ddpm_ema_cifar10 --save_folder clean_model_l2 --num_test $NUM_TEST  --batch_size $BATCH_SIZE --inference_step 500   --model_type $CLSSIFIER 
CUDA_VISIBLE_DEVICES=$GPU_IDS python -m torch.distributed.launch --nproc_per_node=$NUM_GPU --master_port=35369 ddim_attack_eval_lock_l2.py --model_id ../../train/ddpm_ema_cifar10 --save_folder clean_model_l2 --num_test $NUM_TEST  --batch_size $BATCH_SIZE --inference_step 1000  --model_type $CLSSIFIER 
